### ISSUE TITLE
No sonic-pi-pipe executable in path

### ISSUE THREAD

**Issue by MartinDelille** [lpil/sonic-pi-tool#1]
Sorry it may be a GO installation problem but I can't run `sonic-pi-pipe`:

    $ sonic-pi-pipe check
    zsh: command not found: sonic-pi-pipe

**Comment by lpil** [comment]
How did you install `sonic-pi-pipe` ? :)

**Comment by MartinDelille** [comment]
Like that:

```
go get github.com/lpil/sonic-pi-tools/cmd/sonic-pi-pipe
```

**Comment by lpil** [comment]
In which case I think your GOPATH may not been set correctly. 

https://github.com/golang/go/wiki/GOPATH

**Comment by MartinDelille** [comment]
I forgot adding `$GOPATH/bin` to my path... Sorry for disturbing!

**Comment by lpil** [comment]
No problem. Thanks for trying out this tool :D

**Comment by MartinDelille** [comment]
Ok may I ask one more question? How can I use `sonic-pi-log` since it cannot works if the GUI is running? Can we start Sonic Pi server without the GUI?

**Comment by lpil** [comment]
Sure can! If you're on a mac I think you can run it from the application folder somehow.

I'm on Linux and I would download the sonic pi repo, compile it, and then run one of these scripts (I forget which): https://github.com/samaaron/sonic-pi/tree/master/app/server/bin

Probably best to ask one of the sonic pi guys (maybe in their gitter channel) as I've not played with sonic pi in some time, and have huge gaps in my knowledge.

**Comment by MartinDelille** [comment]
It works indeed thanks for the info! I'll send you a PR to document this in the README if you think it worth it.
