### ISSUE TITLE
start-server command improvements

### ISSUE THREAD

**Issue by jtpio** [lpil/sonic-pi-tool#13]
Looking at the current implementation, it looks like the `start-server` command is assuming Mac OS as the host system (https://github.com/lpil/sonic-pi-tool/blob/master/src/lib.rs#L95).

Instead of having a single choice, could there be a list of different paths?
For example, I usually start the Sonic Pi server directly from the root of the git repository, by running `./app/server/bin/sonic-pi-server.rb`.

By having a list of paths, the start-server command would loop through:
```
[
    "/Applications/Sonic Pi.app/server/bin/sonic-pi-server.rb",
    "./app/server/bin/sonic-pi-server.rb"
]
```
and if it finds an existing file, executes it.

**Comment by lpil** [comment]
Yup, that's the plan for the next iteration :)

I was mostly waiting for my next laptop to arrive so I could slap Linux on it and see where various package managers put everything. Would you like to have a go?

**Comment by jtpio** [comment]
Great!
I would love to give it a go, but I will need to get more familiar with Rust before.

**Comment by lpil** [comment]
Honestly I'm not that great with Rust. Feel free to have a go!
