### ISSUE TITLE
Compatibility with sonicpi.vim still present?

### ISSUE THREAD

**Issue by kylebarbour** [lpil/sonic-pi-tool#24]
Hello!

The front page still states that `sonic-pi-tool` is compatible with [`sonicpi.vim`](https://github.com/dermusikman/sonicpi.vim). Unfortunately, I haven't been able to make this work, I believe because of the change from the simpler syntax of `sonic-pi-pipe` to now include `eval` for submitting code to the Sonic Pi server.

Am I missing how to make these two tools work together? In my `.vimrc` I have

````vim
    let g:sonicpi_command="sonic-pi-tool"
````

so it should be attempting to send commands to the right place.

Thanks!

**Comment by kylebarbour** [comment]
Assuming there's no way for `sonic-pi-tool` to accept `stdin` as `sonic-pi-pipe` once did, I've submitted a patch to `sonicpi.vim` to address this issue [here](https://github.com/dermusikman/sonicpi.vim/pull/18).

**Comment by lpil** [comment]
Check out the `eval-stdin` command :)

https://github.com/lpil/sonic-pi-tool#eval-stdin

**Comment by kylebarbour** [comment]
Ah, thanks!

**Comment by lpil** [comment]
Perhaps we could document exactly how to use it with this vim plugin?

**Comment by kylebarbour** [comment]
Would be happy to do that when I figure it out :) I think I still have to extend the plugin to to incorporate the change in syntax since the `eval-stdin` argument is now required to accept standard input.

**Comment by lpil** [comment]
What happens when we set that variable to `sonic-pi-tool eval-stdin` ?

**Comment by kylebarbour** [comment]
After `:let g:sonicpi_command='sonic-pi-tool eval-stdin'`, sending Sonic Pi code to the server (via `<leader>r` &rarr; `SonicPiSendBuffer`) works just fine, but trying to stop the server (via `<leader>S` &rarr; `SonicPiStop`) fails. The terminal output is:

    error: Found argument 'stop' which wasn't expected, or isn't valid in this context

    USAGE:
        sonic-pi-tool eval-stdin

    For more information try --help

The same occurs when trying to do that via the command line (i.e., `$ sonic-pi-tool eval-stdin stop`).

One option would be to extend `sonic-pi-tool` to accept `stdin` as default (without an `eval-stdin` argument), but until then extending the plugin should be as simple as changing `SonicPiSendBuffer()` to

````vim
function! s:SonicPiSendBuffer()
  " Extend compatibility to sonic-pi-tool
  if g:sonicpi_command == "sonic-pi-tool"
    execute "silent w ! " . g:sonicpi_command . " eval-stdin"
  else
    execute "silent w !" . g:sonicpi_command
  endif
endfunction
````

I'd be happy to reupload that and make a pull request.

**Comment by lpil** [comment]
That plugin makes the assumption that every program will have the same interface as the default ruby program, which is not the case. It will need to be updated to remove this assumption.

A sensible approach would be to allow the user to specify each command instead of appending fixed strings.
