### ISSUE TITLE
error: this needs a `'static` lifetime or the `static_in_const` feature, see #35897

### ISSUE THREAD

**Issue by 01010101** [lpil/sonic-pi-tool#25]
Hi,

Got this error on Raspberry Pi 3 / Raspbian Stretch after running :
sudo cargo install  --git https://github.com/lpil/sonic-pi-tool/ --force --verbose

     Running `rustc /root/.cargo/git/checkouts/sonic-pi-tool-647a8cc43a045f33/e0461a474e468c954d61c9d261dd1ff2dbd840b5/src/lib.rs --crate-name lib --crate-type lib -C opt-level=3 -C metadata=da26fcb8219d1c89 -C extra-filename=-da26fcb8219d1c89 --out-dir /tmp/cargo-install.OOLPErj1BELF/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.OOLPErj1BELF/release/deps --extern ansi_term=/tmp/cargo-install.OOLPErj1BELF/release/deps/libansi_term-b026d5281af837e6.rlib --extern nix=/tmp/cargo-install.OOLPErj1BELF/release/deps/libnix-23d5811ff288eae2.rlib --extern rosc=/tmp/cargo-install.OOLPErj1BELF/release/deps/librosc-ae2e7f681f8b7a98.rlib --extern clap=/tmp/cargo-install.OOLPErj1BELF/release/deps/libclap-10e0c1958631b63e.rlib`
error: this needs a `'static` lifetime or the `static_in_const` feature, see #35897
  --> /root/.cargo/git/checkouts/sonic-pi-tool-647a8cc43a045f33/e0461a474e468c954d61c9d261dd1ff2dbd840b5/src/lib.rs:62:24
   |
62 | const ADDR_IN_USE_MSG: &str =
   |                        ^^^^

error: aborting due to previous error

error: failed to compile `sonic-pi-tool v0.1.0 (https://github.com/lpil/sonic-pi-tool/#e0461a47)`, intermediate artifacts can be found at `/tmp/cargo-install.OOLPErj1BELF`

Caused by:
  Could not compile `sonic-pi-tool`.

Caused by:
  process didn't exit successfully: `rustc /root/.cargo/git/checkouts/sonic-pi-tool-647a8cc43a045f33/e0461a474e468c954d61c9d261dd1ff2dbd840b5/src/lib.rs --crate-name lib --crate-type lib -C opt-level=3 -C metadata=da26fcb8219d1c89 -C extra-filename=-da26fcb8219d1c89 --out-dir /tmp/cargo-install.OOLPErj1BELF/release/deps --emit=dep-info,link -L dependency=/tmp/cargo-install.OOLPErj1BELF/release/deps --extern ansi_term=/tmp/cargo-install.OOLPErj1BELF/release/deps/libansi_term-b026d5281af837e6.rlib --extern nix=/tmp/cargo-install.OOLPErj1BELF/release/deps/libnix-23d5811ff288eae2.rlib --extern rosc=/tmp/cargo-install.OOLPErj1BELF/release/deps/librosc-ae2e7f681f8b7a98.rlib --extern clap=/tmp/cargo-install.OOLPErj1BELF/release/deps/libclap-10e0c1958631b63e.rlib` (exit code: 101)

**Comment by lpil** [comment]
Hello! Thanks for the report. What version of rustc are you using?

Development is done with Rust nightly (currently on rustc 1.24.0-nightly (4a7c072fa 2017-12-25)) so nightly may be required.

**Comment by 01010101** [comment]
I have v 1.15.1
In the meantime, it worked correctly with this fork : https://github.com/jtpio/sonic-pi-tool/

I'll ckeck with 1.24.0 and let you know

**Comment by lpil** [comment]
Thanks :)

**Comment by 01010101** [comment]
OK, thx too.
Indeed, the Raspbian Stretch distro does not include the right rustc version nor allows to update to a more recent version via apt.
 
So installation worked with 1.23.0  (766bd11c8 2018-01-01) after doing this 
Uninstall rustc
sudo apt remove rustc
Install rust (as explained here https://www.rust-lang.org/en-US/install.html)
curl https://sh.rustup.rs -sSf | sh

And to later keep rust up to date
rustup update 

Hope it helps and thanks for this great tool.

**Comment by lpil** [comment]
Fab, thanks! I guess the Stretch repo is quite out of date.

Are you happy for this issue to be closed?

**Comment by 01010101** [comment]
Yep, you can close it.
May I suggest you add this requirement in the install section, just in case others bump into the same issue ?

**Comment by lpil** [comment]
Good idea! Will do that now
