### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by Cj-bc** [lpil/sonic-pi-tool#29]
Hello, First of all, Thanks to make this repo! I'm really excited to play Sonic Pi from CLI ;)

I open this issue to inform my (personal) Homebrew formula repository for this repo.
You can use it as:

```bash
$ brew tap Cj-bc/sonic-pi-tool
$ brew install sonic-pi-tool
# or
$ brew install Cj-bc/sonic-pi-tool/sonic-pi-tool
```

Here's the repository for it: https://github.com/Cj-bc/homebrew-sonic-pi-tool
Thanks.

**Comment by lpil** [comment]
Would you like to add a note to the readme documenting this homebrew installation method? A link to the repo would also be appreciated.

**Comment by Cj-bc** [comment]
Thanks! I'm happy to do that ;)
I'll make PR soon

**Comment by juniorctl** [comment]
Using the example from the documentation gives the following output for me:

```
$ brew install Cj-bc/sonic-pi-tool/sonic-pi-tool        
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
git-lfs          jenkins-lts      scrcpy           swiftformat      umlet

==> Tapping cj-bc/sonic-pi-tool
Cloning into '/usr/local/Homebrew/Library/Taps/cj-bc/homebrew-sonic-pi-tool'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Tapped 1 formula (27 files, 23.6KB).
Error: cj-bc/sonic-pi-tool/sonic-pi-tool is a head-only formula
Install with `brew install --HEAD cj-bc/sonic-pi-tool/sonic-pi-tool`
```

Adding the --HEAD flag completed successfully.

**Comment by lpil** [comment]
Thanks for the info @juniorctl . Would you like to make a PR to fix the README?
