### ISSUE TITLE
Ruby error on start-server

### ISSUE THREAD

**Issue by tobyhede** [lpil/sonic-pi-tool#31]
When I run start-server on OSX (Mojave I0.14.5) receive this error `uninitialized constant FFI::Platform::CPU (NameError)`

Anyone seen this before?

**Comment by lpil** [comment]
This looks like a Ruby error coming from Sonic Pi itself. I imagine we're starting the server in the wrong way for the latest version.

Currently we're execing whichever one of these files is found first: https://github.com/lpil/sonic-pi-tool/blob/9edf4e38ea7e94f110cfe9acdd3cbd9fd4728e89/src/lib.rs#L90-L96

Perhaps @samaaron can let us know if that's right

**Comment by tobyhede** [comment]
You gave me an excellent clue, thanks. Pretty sure something in my environment causing the problem. 
Digging through `mainwindow.cpp` I discovered that SonicPi bundles its own Ruby. 

If I execute the server using the bundled Ruby, problem disappears:
`/Applications/Sonic Pi.app/app/server/native/ruby/bin/ruby /Applications/Sonic Pi.app/app/server/ruby/bin/sonic-pi-server.rb`
