### ISSUE TITLE
Run and record a Sonic Pi file

### ISSUE THREAD

**Issue by jtpio** [lpil/sonic-pi-tool#5]
Feature request: run and record a Sonic Pi file.

For example, running:

`sonic-pi-tool record-file path/to/music.rb path/to/music.wav path/to/logs.txt` 

would create two files once there is nothing else to be played:
- `path/to/music.wav`: the audio recorded during the evaluation of the code
- `path/to/logs.txt`: corresponding logs

It would be useful in order to create tracks and automatically export them. Of course, this would not work if there is a `live_loop` in the code.

Sonic Pi exposes the routes `/start-recording`, `/stop-recording` and `/save-recording` to it should be feasible :)

**Comment by lpil** [comment]
Sweet. I was thinking about something like this.

How would you tell when it has stopped playing?

**Comment by lpil** [comment]
How about a `sonic-pi-tool record path/to/out.wav` command that starts recording and then hangs. When the user ctrl-c's or ctrl-d's it then issues the stop and save commands. This seems more generically useful to me.

**Comment by jtpio** [comment]
Good point. It sounds better this way and could be used for live recordings.
